version: '2'

services:

  esn:
    image: linagora/esn:latest
    container_name: esn
    ports:
     - "8080:8080"
    volumes:
      - /home/tlcong/workspace/linagora/open-paas/rse/docker/config:/var/www/docker/config:ro
    env_file:
      - /home/tlcong/workspace/linagora/open-paas/rse/docker/config/oauth.env
    environment:
      - PROVISION=${PROVISION}
      - CONFIG_DIR=/var/www/docker/config
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DBNAME=esn_docker
      - MONGO_TIMEOUT=100000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WEB_HOST=${DOCKER_IP}
      - WEB_PORT=8080
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_INIT_TIMEOUT=${ELASTICSEARCH_INIT_TIMEOUT}

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mongo:
    image: mongo:2.6.5
    command: ["mongod", "--smallfiles"]
    ports:
      - "27017:27017"

  elasticsearch:
    image: elasticsearch:2.2.1
    ports:
      - "9200:9200"
    environment:
      - ELASTICSEARCH_INIT_TIMEOUT=${ELASTICSEARCH_INIT_TIMEOUT}

